#1. Get PRODUCTS order by RATING.VALUE
#http://localhost:12345/products?sort=rating.value,asc

#2. Get PRODUCTS order by PRODUCTINSHOP.SHOP.ADDRESS.NAME
#http://localhost:12345/products?productInShop.shop.address.name=address1

#3. Get REVIEWS order by SHOPID
#http://localhost:12345/reviews/shop/

#4. Post REVIEW to SHOP


POST http://localhost:12345/reviews/product
Content-Type: application/json

{
  "mark": "1",
  "pros": "+",
  "cons": "-",
  "comment": "fantastic",
  "shopId": 2,
  "productId": null,
  "userId": null
}


###
